import json
from pathlib import Path
rows=[]
log=json.loads(Path('papers/lanes/decisions/acquisition-log.json').read_text())
lookup={x['id']:x for x in log}
def add(k,title,authors,year,doi,topics,relevance,evidence='Title, authors, date, abstract and selected methods/examples inspected in acquired full text.',note=None,source=None,path=None,status=None):
 a=lookup.get(k,{})
 path=path or a.get('path')
 status=status or ('acquired' if a.get('ok') or path else 'access_blocked' if a else 'metadata_only')
 url=source or ('https://doi.org/'+doi if doi else a.get('url'))
 rows.append(dict(id='decisions-'+k,title=title,authors=authors,year=year,doi=doi,source_url=url,fulltext_url=a.get('url') if a else None,local_path=path,status=status,topics=topics,relevance=relevance,evidence=evidence,acquisition_note=note or ('Original bytes and SHA256 provenance sidecar retained; pdftotext derivative for reading.' if status=='acquired' else ('Download blocked: '+a.get('error','access restricted')+'. Obtain via author, library or interlibrary loan.' if status=='access_blocked' else 'Primary publisher metadata/abstract or acquired primary bibliography verified; full text not obtained.'))))
C=['adjacent-classification','single-administration']; G=['core-generalizability','d-study']
add('casma-7','A Bootstrap Procedure for Estimating Decision Consistency for Single-Administration Complex Assessments',['Robert L. Brennan','Lei Wan'],2004,None,C+['bootstrap','stratified','mixed-format'],'Boot-i algorithm, stratified resampling, original-vs-replication agreement, impossible-parallel-forms warning.',note='CASMA #7, June 2004; editorial revisions January 25, 2005. Primary PDF title uses A although listing uses The.')
add('casma-9','Manual for BB-CLASS: A Computer Program that uses the Beta-Binomial Model for Classification Consistency and Accuracy',['Robert L. Brennan'],2004,None,C+['beta-binomial','reference-implementation','worked-examples'],'Author manual, HB/LL branches, four-beta moments, effective test length, multiple cut scores, sample input/output; executable is shared quarantine, not executed.',note='CASMA #9 December2004 v1.0. Same manual also in root-acquired BB-CLASS archive; own CASMA copy retained. Manual explicitly identifies implementation judgment in LL effective-length distinctions.')
add('casma-10','A Multinomial Error Model for Tests with Polytomous Items',['Won-Chan Lee'],2005,None,C+['polytomous','conditional-error','compound-multinomial'],'Discrete raw/scale distributions, conditional SEM, reliability, stratified scoring via compound multinomial.')
add('casma-13','Classification Consistency and Accuracy Under the Compound Multinomial Model',['Won-Chan Lee'],2005,None,C+['compound-multinomial','bias-correction','multiple-cuts'],'Conditional and marginal agreement/accuracy, multiple cuts, bias correction; MULT-CLASS oracle spine.',note='CASMA #13 November2005; revisions April2007 and April2008, downloaded revised version.')
add('casma-16','A Strong True-Score Model for Polytomous Items',['Won-Chan Lee','Tianyou Wang','Seonghoon Kim','Robert L. Brennan'],2006,None,C+['dirichlet-multinomial','polytomous'],'Dirichlet-multinomial smoothing, CSEMs, classification consistency/accuracy; comparison data examples.')
add('casma-18','Correcting for Bias in Single-Administration Decision Consistency Indexes',['Robert L. Brennan','Won-Chan Lee'],2006,None,C+['bias-correction','shrinkage','bootstrap'],'Explains naive plug-in bias under binomial/multinomial models, optimized conditional probabilities, parametric bootstrap.')
add('casma-22','Estimating Classification Consistency for Complex Assessments',['Lei Wan','Robert L. Brennan','Won-Chan Lee'],2007,None,C+['simulation','mixed-format','comparison'],'Direct comparison NM, BL, LL, BW and CM; test length, construct equivalence, cut counts and score transformations, bar-exam examples.')
add('casma-27','Classification Consistency and Accuracy for Complex Assessments Using Item Response Theory',['Won-Chan Lee'],2008,None,C+['irt','mixed-format','scale-scores'],'D/P estimation methods, dichotomous and polytomous response distributions; IRT-CLASS theoretical reference.')
add('casma-32','Measurement Error Variability for Advanced Placement (AP) Composite Scores and Grades',['Benjamin J. Andrews','Michael J. Kolen','Won-Chan Lee'],2011,None,C+['conditional-error','grades','compound-multinomial'],'Unidimensional/multidimensional IRT and compound-multinomial CSEM of composites and categorical grades.')
add('optimization-2021','A Short Note on Optimizing Cost-Generalizability via a Machine-Learning Approach',['Zhehan Jiang','Dexin Shi','Christine DiStefano'],2021,'10.1177/0013164421992112',G+['optimization','simulated-annealing','costs','osce'],'Integer facet allocation to minimize cost under absolute reliability target; compare Lagrange solutions. Apparent reversed constraint sign and exchanged example counts require reconciliation.',note='Complete PMC HTML acquired (with equations/table content). Selected fulltext methods read and independent arithmetic checked. Printed ni=2,no=10 yields .8716707, swapped10,2 yields .9392471 from stated components; see report, not silently normalized.')
add('mixed-format-classification-2015','Methods for Evaluating Composite Reliability, Classification Consistency, and Classification Accuracy for Mixed-Format Licensure Tests',['Tim Moses','Sooyeon Kim'],2015,'10.1177/0146621614563067',C+['mixed-format','rater-design','composite-weights'],'Compares single/double CR scoring and weighting; links reliability changes to classification consistency/accuracy; LL model fitting can fail at extreme weighting.',note='Complete PMC HTML acquired; journal issue2015, first online December22,2014.')
add('huynh-proceedings-1978','Solutions for Some Technical Problems in Domain-Referenced Mastery Testing: Final Report',['Huynh Huynh','Joseph C. Saunders'],1980,None,C+['beta-binomial','decision-theory','mastery','bibliography','program-listings'],'387-page primary project report with17 papers: minimax/Bayesian passing scores, budget, agreement/kappa inference, false decisions, sample sizes and sensitivity.',note='ERIC ED320928 August1980 full collected report acquired intact. Filename reflects discovery through1978 component; catalogue date corrected1980. Scanned equations require visual confirmation; not all387 pages closely read.')
add('writing-optimization-eric','The Preferability of Constrained Optimization in Determining the Number of Prompts, Modes of Discourse, and Raters in a Direct Writing Assessment',['Jay Parkes','Hoi K. Suen'],1995,None,G+['integer-programming','branch-and-bound','writing','nested-design'],'Early operational integer allocation;50students,3raters; four policy scenarios for prompts/modes/raters.',note='ERIC ED390945 NCME conference paper April1995,27pages; title/abstract/design and optimization discussion inspected.')
add('reliability-decisions-umn','Reliability of Test Scores and Decisions',['Ross E. Traub','Glenn L. Rowley'],1980,'10.1177/014662168000400406',['classification-review','loss-functions','criterion-referenced'],'Primary review separates threshold, linear, quadratic loss and accuracy vs consistency; warns against treating differently defined coefficients interchangeably.',note='UMN Digital Conservancy official API PDF acquired. Issue Fall1980, copyright footer1981; year follows journal issue1980. Selected taxonomy/method discussions read.')
add('cut-score-bootstrap-2024','Forming intervals of predicted total scores for cut-off scores evaluation: a generalizability theory application with Bootstrapping',['Zhehan Jiang','Jinying Ouyang','Dexin Shi','Junhao Pan','Lingling Xu','Fen Cai'],2024,'10.1007/s12144-024-06306-9',G+['bootstrap','cut-scores','predc','ordinal'],'LMM resampling IPTS and PredC proportion overlapping cut; compare3bootstrap schemes. PredC is an uncertainty-overlap criterion, not classification accuracy.',evidence='Primary Springer abstract, date/authors/references and exposed appendix read; full article not acquired.',note='Ordinary publisher PDF returned access HTML, rejected. Peking University handle20.500.11897/720881 has no attached files. Landing exposes R-code appendix images; fulltext/data via author request.')
add('cost-effectiveness-2022','Cost-Effectiveness Analysis in Performance Assessments: A Case Study of the Objective Structured Clinical Examination',['Zhehan Jiang','Jinying Ouyang','Li Li','Yuting Han','Lingling Xu','Ren Liu','Junhua Sun'],2022,'10.1080/10872981.2022.2136559',G+['costs','osce','precog-a'],'PRECOG-A integrates financial drivers and psychometric effectiveness; distinguishes cost model construction from G-study projection.',note='Complete PMC HTML acquired. Primary abstract and PRECOG-A workflow inspected; not an owned optimizer implementation.')
add('cut-scores-yin-sconing','Estimating Standard Errors of Cut Scores for Item Rating and Mapmark Procedures: A Generalizability Theory Approach',['Ping Yin','James Sconing'],2008,'10.1177/0013164407301546',G+['standard-setting','cut-scores','angoff','bookmark'],'Two G-designs and four D-designs for panelist/judgment cut variability; distinct from candidate-score measurement error.',note='Primary article PDF mirrored by CiteSeerX acquired; online2007 preprint footer, final EPM68(1)25–41 in2008 verified publisher. Whole article17pages.')
add('minlp-performance-2016','Optimizing the Costs and GT based reliabilities of Large-scale Performance Assessments',['Yon Soo Suh','Dasom Hwang','Meiling Quan','Guemin Lee'],2016,'10.1007/978-3-319-38759-8_13',G+['optimization','mixed-integer-nonlinear','school-level','nested-design','costs'],'MINLP with branch-and-bound for school-level reliability; person nested school crossed task/rater; budgets and realistic facet bounds.',note='Full Quantitative Psychology Research proceedings volume acquired intact from institutional education repository; relevant chapter printedpp173–185. Do not confuse full-volume PDF acquisition with reading all chapters.')
add('criterion-analysis-1982','Criterion-referenced measurement: Its main applications, problems and findings',['Wim J. van der Linden'],1982,'10.1016/0191-765X(82)90012-X',['criterion-referenced','decision-theory','review'],'Primary review distinguishes scoring interpretation, item/test analysis and mastery-testing optimization.',source='https://research.utwente.nl/en/publications/criterion-referenced-measurement-its-main-applications-problems-a/')
add('agreement-kane-brennan-1980','Agreement Coefficients as Indices of Dependability for Domain-Referenced Tests',['Michael T. Kane','Robert L. Brennan'],1980,'10.1177/014662168000400111',['core-generalizability','loss-functions','chance-correction','mastery'],'General agreement framework unifies threshold and squared-error indices, corrected/uncorrected chance; design and interpretation prerequisites.')
add('lagrange-complex-2024','New roles of Lagrange multiplier method in generalizability theory: Inference of estimating the optimal sample size for teaching ability evaluation of college teachers',['Guangming Li'],2024,'10.1371/journal.pone.0307710',G+['optimization','nested-design','lagrange','teaching'],'Derivations for(s:t)×i,(s:t)×(i:v),(s:t)×(i:v)×o; continuous optimum students/items given dimensions/occasions.17students,4items example.',note='Primary PLOS PDF acquired, selected equations and empirical example read. Step4 recommends rounding; independently enforce integer budget feasibility instead of treating rounding as proof.')
add('bifactor-decisions-2023','Extending Applications of Generalizability Theory-Based Bifactor Model Designs',['Walter P. Vispoel','Hyeryung Lee','Tingting Chen','Hyeri Hong'],2023,'10.3390/psych5020036',G+['bifactor','sem','absolute-relative','prophecy','subscale'],'Absolute and relative GT bifactor components and item/occasion prophecy formulas, BFI-2 examples, coefficients/cut-specific dependability.',note='MDPI static publisher PDF acquired, pp545–575. Formulas/code/sample-data availability inspected; root notified for supplement ingestion.')
add('beta-moments-hanson-1991','Method of Moments Estimates for the Four-Parameter Beta Compound Binomial Model and the Calculation of Classification Consistency Indexes',['Bradley A. Hanson'],1991,None,C+['beta-binomial','method-of-moments','numerical-methods'],'ACT91-5 exact computational spine for BB-CLASS four-parameter moments and agreement integration.',note='ERIC ED344945 official report September1991 acquired; title/introduction/computation sections inspected.')
add('norm-exam-2025','Challenging the norm: Length of exams determined by classification accuracy or reliability',['Stefan K. Schauber','Matt Homer'],2025,'10.1111/medu.15742',['adjacent-classification','test-length','cut-scores','medical-education'],'Resampling52,500syntheticexams across lengths/cuts: classification accuracy changes with cuts; global reliability largely does not; false-pass/fail tradeoffs.',note='PublisherPDF403; author accepted fulltext acquired from UniversityLeeds WhiteRose institutional repository, CC-BY4.0. SupplementFigure1 is separately available but not counted asarticle.',source='https://eprints.whiterose.ac.uk/id/eprint/226675/')
for k,title,au,y,doi,topics,rel in [
 ('mastery-index-1977','An Index of Dependability for Mastery Tests',['Robert L. Brennan','Michael T. Kane'],1977,'10.1111/j.1745-3984.1977.tb00045.x',G+['cut-specific','squared-error'],'Classic cut-specific squared-error dependability; do not equate with raw classification-agreement probability.'),
 ('huynh-decisions-1976','On the Reliability of Decisions in Domain-Referenced Testing',['Huynh Huynh'],1976,'10.1111/j.1745-3984.1976.tb00016.x',C+['beta-binomial','mastery'],'Foundational one-admin beta-binomial decision consistency; original journalpp253–264.'),
 ('livingston-lewis-1995','Estimating the Consistency and Accuracy of Classifications Based on Test Scores',['Samuel A. Livingston','Charles Lewis'],1995,'10.1111/j.1745-3984.1995.tb00462.x',C+['weighted-composites','effective-test-length','beta-binomial'],'General weighted-score effective-length plus four-beta model; BB-CLASS manual gives sample output and implementation ambiguities.'),
 ('hanson-brennan-1990','An Investigation of Classification Consistency Indexes Estimated Under Alternative Strong True Score Models',['Bradley A. Hanson','Robert L. Brennan'],1990,'10.1111/j.1745-3984.1990.tb00753.x',C+['model-fit','beta-binomial'],'Model-fit comparisons show simple beta-binomial may fit inadequately; assess fit before estimating consistency.'),
 ('conditional-raw-brennan-1998','Raw-Score Conditional Standard Errors of Measurement in Generalizability Theory',['Robert L. Brennan'],1998,'10.1177/014662169802200401',['core-generalizability','conditional-error','absolute-relative','stratified'],'Unified conditional absolute/relative SEM for single/multifacet and multivariate designs; across-person dependence differs.'),
 ('teaching-optimization-2014','A Practical Solution to Optimizing the Reliability of Teaching Observation Measures Under Budget Constraints',['J. Patrick Meyer','Xiang Liu','Andrew J. Mashburn'],2014,'10.1177/0013164413508774',G+['nested-design','costs','lagrange'],'Closed-form facet allocations for one crossed and three nested observation designs; component combination when changing designs.')]:
 add(k,title,au,y,doi,topics,rel,evidence='Primary publisher title/authors/date/abstract inspected; fulltext unavailable in lane. Author mirror indexed for Meyer but actual download404.')
for k,title,au,y,doi,rel in [
 ('woodward-joe-1973','Maximizing the Coefficient of Generalizability in Multi-Facet Decision Studies',['J. Arthur Woodward','George W. Joe'],1973,'10.1007/bf02291112','Early multifacet allocation optimization; original Psychometrika38,173–181.'),
 ('resource-constraints-1990','The Optimization of Generalizability Studies with Resource Constraints',['George A. Marcoulides','Zvi Goldstein'],1990,'10.1177/0013164490504004','Classic two-facet Lagrange allocation under cost-product constraint; descendants reproduce worked example.'),
 ('integer-generalizability-1991','Maximizing the Coefficient of Generalizability in Decision Studies',['Zvi Goldstein','George A. Marcoulides'],1991,'10.1177/0013164491511006','Discrete candidates/rounding under budget; primary acquired optimization2021 bibliography confirms79–88.'),
 ('multivariate-conditions-1991','Selecting the Number of Observations in Multivariate Measurement Studies Under Budget Constraints',['George A. Marcoulides','Zvi Goldstein'],1991,'10.1177/0013164491513005','Multivariate two-facet resource allocation, extensions discussed.'),
 ('multivariate-optimization-1992','The Optimization of Multivariate Generalizability Studies with Budget Constraints',['George A. Marcoulides','Zvi Goldstein'],1992,'10.1177/0013164492052002005','Covariance/weight-aware multivariate budget optimization.'),
 ('power-constraints-1993','Maximizing Power in Generalizability Studies Under Budget Constraints',['George A. Marcoulides'],1993,'10.3102/10769986018002197','Minimize mean error variance to improve power under budgets; alternate JSTORDOI10.2307/1165086 identifies same paper.'),
 ('power-error-1995','Designing Measurement Studies Under Budget Constraints: Controlling Error of Measurement and Power',['George A. Marcoulides'],1995,'10.1177/0013164495055003005','Budget-constrained measurement error and statistical power objectives.'),
 ('variable-cost-1997','Optimizing Measurement Designs with Budget Constraints: The Variable Cost Case',['George A. Marcoulides'],1997,'10.1177/0013164497057005006','Costs vary within facets; avoid assuming one constant unit cost perfacet.'),
 ('signal-noise-1977','Signal/Noise Ratios for Domain-Referenced Tests',['Robert L. Brennan','Michael T. Kane'],1977,'10.1007/bf02295983','Signal/noise formulation for domain-referenced scores, different loss/decision interpretations.'),
 ('precision-kane-1996','The Precision of Measurements',['Michael T. Kane'],1996,'10.1207/s15324818ame0904_4','Precision relative to purpose-specific error tolerance, not universal reliability threshold.'),
 ('livingston-1972','Criterion-Referenced Applications of Classical Test Theory',['Samuel A. Livingston'],1972,'10.1111/j.1745-3984.1972.tb00756.x','Squared deviations from criterion replaces deviations frommean; CTT predecessor, not multifacetGT.'),
 ('huynh-inference-1979','Statistical Inference for Two Reliability Indices in Mastery Testing Based on the Beta-Binomial Model',['Huynh Huynh'],1979,'10.3102/10769986004003231','Agreement/kappa SEs, tables and program; confidence intervals, hypothesis tests,minsample. Related1978memorandum in acquired1980report has differenttitle.')]:
 add(k,title,au,y,doi,G+(['adjacent-classification'] if k.startswith('huynh') or k=='livingston-1972' else ['design-interpretation']),rel,evidence='Primary publisher/Crossref metadata or acquired primary-paper bibliography inspected; abstract inspected when accessible. Fulltext not obtained; no implementation conclusions inferred from metadata alone.')
for k,title,au,y,path,rel in [
 ('mult-class-manual','Program MULT-CLASS (Version 3.0) for Multinomial and Compound-Multinomial Classification Consistency and Accuracy',['Won-Chan Lee'],2008,'quarantine/references/mult-class/manual v3.0.pdf','July2008manual, raw/scale, mixed-format, cutoff controls and archiveddich/mixed input-output examples.'),
 ('irt-class-manual','Program IRT-CLASS for Item Response Theory Classification Consistency and Accuracy (Version 2.0)',['Won-Chan Lee','Michael J. Kolen'],2008,'quarantine/references/irt-class/IRT-CLASS 2.0 manual.pdf','March2006revisedApril2008manual, control/item/theta/scaled-score/cutoff file contracts and suppliedexample.out.'),
 ('nm-class-manual','Program NM-CLASS for Normal Approximation Classification Consistency and Accuracy (Version 1.0)',['Stella Y. Kim'],2019,'quarantine/references/nm-class/NM-CLASS_manual_v1.pdf','August2019R-code manual, normal approximation PengSubkoviak1980 and KimLee2019; example.dat and standaloneR available.')]:
 add(k,title,au,y,None,C+['reference-implementation','manual','worked-examples'],rel,evidence='Root-acquired author archive manual title/date/input requirements/sample output inspected; text derivatives created, references not executed.',note='Shared root-owned quarantine artifact; root acquisition manifests preserve source/archive. No duplicate PDF downloaded; no executable/source was run.',source='https://brennancrickgenova.org/classification-decision-consistency-programs/',path=path,status='acquired')
Path('papers/lanes/decisions/catalogue.json').write_text(json.dumps(rows,indent=2)+'\n')
from collections import Counter
print(len(rows),Counter(x['status'] for x in rows))
